name: archiever
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #State manamagement
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  #DI
  get_it: ^7.7.0


  freezed: ^2.5.2
  

  dartz: ^0.10.1


  freezed_annotation: ^2.4.1


  json_serializable: ^6.8.0

  
  json_annotation: ^4.9.0
  
  archive: ^3.5.0

  permission_handler: ^11.3.1

  dio: ^5.4.3+1

  path_provider: ^2.1.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # code generators
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

